"""Generated Pydantic v2 models for cxg-author-probe.

DO NOT EDIT — regenerate via 'make models' (scripts/generate_models.py).
Source of truth: schemas/*.schema.json.
"""
# generated by datamodel-codegen:

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Format(Enum):
    """
    Source-format hint. Selects which reader was used.
    """

    h5ad = 'h5ad'
    anndata_zarr = 'anndata-zarr'
    tiledbsoma = 'tiledbsoma'
    parquet = 'parquet'


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str
    """
    Fully-qualified URL or path the probe read from.
    """
    format: Format
    """
    Source-format hint. Selects which reader was used.
    """
    etag: str | None = None
    """
    Server cache-validator (HTTP ETag) if available — used for invalidation across Census releases.
    """
    size_bytes: int | None = None
    """
    Total source-file size if cheaply available; informational only.
    """


class ProbeMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    probe_bytes: int | None = None
    """
    Total bytes-on-wire during the probe.
    """
    probe_gets: int | None = None
    """
    Number of HTTP/range fetches during the probe.
    """
    probe_time_s: float | None = None
    reader: str | None = None
    """
    Reader module that produced this probe, e.g. 'cxg_author_probe.readers.h5ad'.
    """
    package_version: str | None = None
    """
    Version of cxg-author-probe at probe time.
    """
    probed_at: AwareDatetime | None = None


class PickerKind(Enum):
    claude_code_subagent = 'claude-code-subagent'
    anthropic_api = 'anthropic-api'
    human = 'human'
    rule_based = 'rule-based'
    other = 'other'


class Picker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: PickerKind | None = None
    model: str | None = None
    """
    Model identifier, e.g. 'claude-sonnet-4-6'. Empty for non-LLM kinds.
    """
    version: str | None = None
    """
    Picker prompt version or package version that produced this pick.
    """


class PicksV1(BaseModel):
    """
    Output of the picker stage. One file per dataset; produced by a Claude Code sub-agent, an Anthropic-API call, or any other LLM driver — even a human. The schema does not constrain *who* produced the picks, only that they match the probe.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['picks-v1']
    dataset_id: str
    probe_ref: str | None = None
    """
    Path to the probe-v1 JSON this pick was derived from, or its content-hash. Used to detect schema drift before assembly.
    """
    picks: list[str]
    """
    Obs column names selected as author cell-type fields. Empty array is valid — means 'no author cell-type column present in this dataset'.
    """
    reasoning: str | None = None
    """
    One-sentence justification, for audit and disagreement triage.
    """
    picker: Picker | None = None
    picked_at: AwareDatetime | None = None


class PullMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pull_bytes: int | None = None
    pull_gets: int | None = None
    pull_time_s: float | None = None
    package_version: str | None = None
    pulled_at: AwareDatetime | None = None


class PulledV1(BaseModel):
    """
    Metadata sidecar for the full-column pull stage. The actual joinids + values live in a sibling Parquet (or .npz) file referenced by 'data_path'; this JSON describes shape, dtype, and provenance.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['pulled-v1']
    dataset_id: str
    probe_ref: str | None = None
    picks_ref: str | None = None
    picks: list[str]
    """
    Columns actually pulled (subset of picks-v1.picks; missing columns are noted under 'missing').
    """
    missing: list[str] | None = None
    """
    Columns that were requested but absent from the source.
    """
    data_path: str
    """
    Path to the data sidecar — .parquet by default, with columns observation_joinid + one per picked column.
    """
    n_cells: int = Field(..., ge=0)
    pull_meta: PullMeta | None = None


class ColumnKind(Enum):
    """
    How the column is stored in the source. 'categorical' = code+category encoding (AnnData / pandas). 'array' = plain 1D array. 'group' = source-specific compound (rare). 'unknown' = reader did not classify.
    """

    categorical = 'categorical'
    array = 'array'
    group = 'group'
    unknown = 'unknown'


class ColumnDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: ColumnKind
    """
    How the column is stored in the source. 'categorical' = code+category encoding (AnnData / pandas). 'array' = plain 1D array. 'group' = source-specific compound (rare). 'unknown' = reader did not classify.
    """
    dtype: str
    """
    Normalised dtype string. Categorical codes use the codes' dtype (e.g. 'int8'). Arrays use their underlying dtype (e.g. 'float32', 'object', 'bool').
    """
    n_unique: int | None = None
    """
    Number of distinct values in the column. Cheap for categorical (== n_categories). May be null when prohibitively expensive (e.g. float columns) or unsupported by the reader.
    """
    n_unique_estimated: bool | None = False
    """
    True if n_unique was computed by sampling rather than a full scan. Always false for categorical.
    """
    n_categories: int | None = None
    """
    Length of the categories table for categorical columns; null otherwise. Legacy alias of n_unique for kind=='categorical'.
    """
    shape: list[int] | None = None
    """
    Underlying array shape if applicable; e.g. [n_cells] for plain 1D arrays.
    """
    encoding: str | None = None
    """
    Source-specific hint (e.g. 'anndata-categorical', 'csr_matrix-indptr') for downstream consumers that care.
    """
    sample: list[Any] | None = Field(None, max_length=20)
    """
    Head sample of up to 20 column values, normalised to JSON-serialisable. For categoricals, decoded to category labels. For bytes, decoded to UTF-8 strings.
    """


class ProbeV1(BaseModel):
    """
    One JSON file per dataset, emitted by `cxg-author probe`. Describes the obs schema, per-column sample, and probe cost — without ever reading the expression matrix. Source-format agnostic: the same schema serves h5ad, anndata-zarr, tiledbsoma, parquet, …
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['probe-v1']
    """
    Consumers MUST gate on this string.
    """
    dataset_id: str
    """
    Stable identifier for the source dataset. For CELLxGENE this is the CxG dataset_id UUID.
    """
    source: Source
    n_cells: int = Field(..., ge=0)
    """
    Number of rows in obs.
    """
    columns: dict[str, ColumnDescriptor]
    """
    Map: obs column name -> descriptor + sample. `_index` and other source-internal pseudo-columns are filtered out at probe time.
    """
    probe_meta: ProbeMeta

